services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    env_file: .env
    ports:
      - 3000:3000
    restart: unless-stopped